# Generated by Django 5.1.2 on 2024-10-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_city_customer_district_customer_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='Thana',
        ),
    ]
