# Generated by Django 5.1.2 on 2024-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, default='vendor_logos/default_banner.jpeg', upload_to='vendor_banners/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, default='vendor_logos/default_logo.jpeg', upload_to='vendor_logos/'),
        ),
    ]
