# Generated by Django 5.1.1 on 2024-09-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_varient_images/'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
