# Generated by Django 5.1.1 on 2024-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(blank=True, default='New Name', max_length=15, null=True),
        ),
    ]
