# Generated by Django 5.1.1 on 2024-10-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_coupon_coupon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
