# Generated by Django 5.1.1 on 2024-10-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_alter_orderitems_options_cartitems_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'ordering': ['-id'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Item'},
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
