# Generated by Django 5.1.2 on 2024-10-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('acitvate', 'ACTIVATE'), ('completed', 'COMPLETED')], default='activate', max_length=10),
        ),
    ]
