# Generated by Django 5.1.2 on 2024-11-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_contactus_faq_contactus_form_footer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='main_logo/')),
            ],
        ),
    ]
